services:
    wordpress:
        image: wordpress:6.2-php8.1
        hostname: wordpress
        ports:
            - 8080:80
        environment:
            WORDPRESS_DB_HOST: db
            WORDPRESS_DB_USER: e2e
            WORDPRESS_DB_PASSWORD: e2e
            WORDPRESS_DB_NAME: wordpress
            WORDPRESS_DEBUG: 1
            WORDPRESS_CONFIG_EXTRA: |
                define('WP_HOME', 'http://' . $$_SERVER['HTTP_HOST']);
                define('WP_SITEURL', 'http://' . $$_SERVER['HTTP_HOST']);
        volumes:
            - wordpress:/var/www/html
            - ../:/var/www/html/wp-content/plugins/comment-saver/
            - ./mu-plugins:/var/www/html/wp-content/mu-plugins
        depends_on:
            db:
                condition: service_healthy
    wpcli:
        image: wordpress:cli-2.8-php8.1
        user: "33:33"
        environment:
            WORDPRESS_DB_HOST: db
            WORDPRESS_DB_USER: e2e
            WORDPRESS_DB_PASSWORD: e2e
            WORDPRESS_DB_NAME: wordpress
        volumes:
            - wordpress:/var/www/html
            - ../:/var/www/html/wp-content/plugins/comment-saver/
        working_dir: /var/www/html
        depends_on:
            wordpress:
                condition: service_started
    db:
        image: mysql:5.7
        restart: always
        environment:
            MYSQL_DATABASE: wordpress
            MYSQL_USER: e2e
            MYSQL_PASSWORD: e2e
            MYSQL_RANDOM_ROOT_PASSWORD: '1'
        volumes:
            - db:/var/lib/mysql
        healthcheck:
            test: mysql wordpress --user=e2e --password=e2e --silent --execute "SELECT 1;"
            interval: 30s
            timeout: 10s
            retries: 5
    e2e:
        image: mcr.microsoft.com/playwright:v1.35.0-jammy
        volumes:
            - .:/e2e
        working_dir: /e2e
        depends_on:
            wordpress:
                condition: service_started
volumes:
    wordpress:
    db:
